language: cpp
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential gcc g++-4.8 llvm clang-3.4 cmake nodejs python2.7 default-jre
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget http://launchpadlibrarian.net/151967526/emscripten_1.4.9~20130620~0ad8724-1ubuntu1_amd64.deb
#  - sudo dpkg -i "emscripten_1.4.9~20130620~0ad8724-1ubuntu1_amd64.deb"
  - clang --version
  - g++ --version
  - python --version
  - node --version
  - java -version
  - cmake
  - NUM_CORES=`cat /proc/cpuinfo | grep "^cpu cores" | uniq | cut -c 13- -`
  - echo $NUM_CORES
  - MYTEST=n
  - echo -$MYTEST "BLUB"

script:
  - true
