language: cpp
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential gcc g++-4.8 llvm clang-3.4 cmake nodejs python2.7 default-jre
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - clang --version
  - g++ --version
  - python --version
  - node --version
  - java -version
  - cmake
  - NUM_CORES=`cat /proc/cpuinfo | grep "^cpu cores" | uniq | cut -c 13- -`
  - echo $NUM_CORES
  - MYMAKE="make -j$NUM_CORES "
  - echo $MYMAKE

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -zxf emsdk-portable.tar.gz
  - rm emsdk-portable.tar.gz
  - cd emsdk_portable
  - ./emsdk update
  - ./emsdk install latest emscripten-master clang-master-64bit sdk-master-64bit
  - cd clang/fastcomp/src
  - mkdir mybuild
  - cd mybuild
  - ../configure --enable-optimized --disable-assertions --enable-targets=host,js
  - eval $MYMAKE
  - cd ../../../../..
  - tar -czf build.tar.gz emsdk_portable/clangfastcomp/src/mybuild/
  - ls -la
  - ./emsdk activate latest
  - source ./emsdk_env.sh

script:
  - true

deploy:
  
