language: cpp
sudo: required
before_install:
  - if [ 0 -ne `sudo apt-get update -qq` ] then sudo apt-get update -qq; fi
  - sudo apt-get install -qq cmake nodejs python2.7 default-jre

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -zxf emsdk-portable.tar.gz
  - rm emsdk-portable.tar.gz
  - cd emsdk_portable
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - ls -la clang
  - ls -la zips

script: true
