language: cpp
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake nodejs python2.7 default-jre
  - python --version
  - node --version
  - java -version
  - cmake
  - NUM_CORES=`cat /proc/cpuinfo | grep "^cpu cores" | uniq`
  - echo $NUM_CORES

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -zxf emsdk-portable.tar.gz
  - rm emsdk-portable.tar.gz
  - cd emsdk_portable
  - ./emsdk update
  - ./emsdk install latest emscripten-master
  - ./emsdk activate latest
  - source ./emsdk_env.sh

script:
  - ls -la
  - ls -la clang/fastcomp
  - ls -laR clang/fastcomp/build_master_64
