language: cpp
sudo: required
before_install:
  - cat /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq emscripten
  - clang --version
  - g++ --version
  - python --version
  - node --version
  - java -version
  - cmake
  - NUM_CORES=`cat /proc/cpuinfo | grep "^cpu cores" | uniq | cut -c 13- -`
  - echo $NUM_CORES
  - MYTEST=n
  - echo -$MYTEST "BLUB"

source:
  - true
