language: cpp
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake nodejs python2.7 default-jre

install:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar -zxf emsdk-portable.tar.gz
  - rm emsdk-portable.tar.gz
  - cd emsdk_portable
  - ls -la
  - ./emsdk update
  - ./emsdk install latest
